version: 2

workflows:
  version: 2
  test_deploy:
    jobs:
      - fetch_config
      - test:
          requires:
            - fetch_config
      - build:
          requires:
            - test
      - deploy-api:
          filters:
            branches:
              only: master
          requires:
            - test
      - deploy-frontend:
          filters:
            branches:
              only: master
          requires:
            - build

jobs:
    fetch_config:
      docker:
        - image: cibuilds/aws:latest
      steps:
        - checkout
        - run: aws s3 cp s3://naish-config-vars/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_PROJECT_REPONAME}-production.yaml env.yml --region eu-west-2
        - persist_to_workspace:
            root: .
            paths: env.yml
    test:
      docker:
        - image: circleci/node:8.10.0
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run: npm install
        - run: npm test
        - persist_to_workspace:
            root: .
            paths: '*'
    build:
      docker:
        - image: circleci/node:8.10.0
      steps:
        - attach_workspace:
            at: .
        - run: npm run build
        - persist_to_workspace:
            root: .
            paths: '*'
    deploy-api:
      docker:
        - image: circleci/node:8.10.0
      steps:
        - attach_workspace:
            at: .
        - run: ./deploy-api.sh
    deploy-frontend:
      docker:
        - image: cibuilds/aws:latest
      steps:
        - attach_workspace:
            at: .
        - run: aws s3 sync dist s3://wedding-website-frontend --region eu-west-2 --exclude "*" --include "*.html" --include "service-worker.js" --acl "public-read" --cache-control "max-age=0" --delete
        - run: aws s3 sync dist s3://wedding-website-frontend --region eu-west-2 --exclude "*" --include "*.ico" --include "*.txt" --acl "public-read" --cache-control "max-age=86400" --delete
        - run: aws s3 sync dist s3://wedding-website-frontend --region eu-west-2 --exclude "*" --include "*app.*.js" --include "*app.*.css" --include "*.png" --include "*.otf" --acl "public-read" --cache-control "public, max-age=31536000" --delete
